spring:
   datasource:
      username: game-database
      password: game-database
      url: jdbc:mysql://localhost:3306/game-database
      
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      
   sql:
      init:
         mode: never